/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import negocio.clsNegocio;



public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        
        grupoLaboral.add(this.rbtnSi);
        grupoLaboral.add(this.rbtnNo);
        
        grupoSalarial.add(this.rbtnIgual);
        grupoSalarial.add(this.rbtnMayor);
        grupoSalarial.add(this.rbtnMenor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLaboral = new javax.swing.ButtonGroup();
        grupoSalarial = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblLaboral = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtnSi = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        lblIngreso = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtnMenor = new javax.swing.JRadioButton();
        rbtnIgual = new javax.swing.JRadioButton();
        rbtnMayor = new javax.swing.JRadioButton();
        btnEvaluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 220, -1));

        lblLaboral.setText("Labora Actualmente:");
        getContentPane().add(lblLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnSi.setText("Si");
        jPanel1.add(rbtnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        rbtnNo.setText("No");
        jPanel1.add(rbtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, 80));

        lblIngreso.setText("Ingreso Mensuales");
        getContentPane().add(lblIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnMenor.setText("Menores a 1500");
        jPanel2.add(rbtnMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        rbtnIgual.setText("Iguales a 1500");
        jPanel2.add(rbtnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        rbtnMayor.setText("Mayores a 1500");
        jPanel2.add(rbtnMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 190, 120));

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        clsNegocio negocio=new clsNegocio();
        JOptionPane.showMessageDialog(null, negocio.ejecutar(txtNombre.getText(), rbtnSi.isSelected(),
                rbtnMenor.isSelected(), rbtnIgual.isSelected(), rbtnMayor.isSelected()));
    }//GEN-LAST:event_btnEvaluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.ButtonGroup grupoLaboral;
    private javax.swing.ButtonGroup grupoSalarial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblLaboral;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JRadioButton rbtnIgual;
    private javax.swing.JRadioButton rbtnMayor;
    private javax.swing.JRadioButton rbtnMenor;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnSi;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
